[font]
size = 14.0

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

# [font.bold]
# family = "DMMono"
# style = "Bold"
#
# [font.bold_italic]
# family = "DMMono"
# style = "Bold Italic"
#
# [font.italic]
# family = "DMMono"
# style = "Italic"
#
# [font.normal]
# family = "DMMono"
# style = "Regular"

# Tmux doesn't implement 'Kitty key protocol' (not yet, but it's currently being worked on), 
# which is the protocol used by alacritty, meaning key combinations like Ctrl+Enter are being
# interpreted as just Enter. As a workaround for Ctrl+Enter, i've changed Ctrl+Enter in alacritty
# to Ctrl+Y, and in my neovim config, i optionally bind autocomplete to Ctrl+Y or Ctrl+Enter
# depending on whether I'm running neovim in alacritty or not.
[[keyboard.bindings]]
key = "Return"
mods = "Control"
chars = "\u0019" # This is Ctrl+Y
