tap "jstkdng/programs", trusted: true
tap "anomalyco/tap"

brew "antidote"
brew "ast-grep"
brew "bat"
brew "chafa"
brew "delta"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "hyperfine"
brew "jstkdng/programs/ueberzugpp"
brew "lazygit"
brew "neovim", args: ["HEAD"]
brew "anomalyco/tap/opencode"
brew "resvg"
brew "ripgrep"
brew "rustup"
brew "scc"
brew "stow"
brew "tldr"
brew "tmux"
brew "tree-sitter"
brew "pandoc"
brew "typst"
brew "uv"
brew "yazi"
brew "zig"
brew "zoxide"
